name: Build
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Pull MUMPS
      run: |
        curl --output ${{ runner.temp }}/MUMPS_5.7.3.tar.gz ${{ secrets.MUMPS_URL }}/MUMPS_5.7.3.tar.gz
        tar -xzf ${{ runner.temp }}/MUMPS_5.7.3.tar.gz -C ${{ runner.temp }}
        cp -r ${{ runner.temp }}/MUMPS_5.7.3/* ${{ github.workspace }}
        ls -lAh ${{ github.workspace }}
      shell: bash
    - name: Prepare pulling cmake installed libraries
      run: |
        echo "CMAKE_INSTALL_PREFIX=${{ runner.TEMP }}" >> $GITHUB_ENV
    - name: Download GKlib
      uses: dawidd6/action-download-artifact@v6
      with: 
        name: gklib-linux-gcc
        repo: worc4021/GKlib
        path: ${{ runner.TEMP }}
        workflow: ci.yml
    - name: Download METIS
      uses: dawidd6/action-download-artifact@v6
      with: 
        name: metis-linux-gcc
        repo: worc4021/METIS
        path: ${{ runner.TEMP }}
        workflow: ci.yml
    - uses: ./.github/actions/oneapi
      with:
        LINUX_COMPONENTS: 
    # - name: Setup Ninja
    #   uses: seanmiddleditch/gha-setup-ninja@master
    # - name: Setup cmake
    #   uses: jwlawson/actions-setup-cmake@v2
    #   with:
    #     cmake-version: '3.29.x'
    # - name: Configure
    #   run: |
    #     cmake --preset linux-gcc-release-config -DBQPD_BUILD_MATLAB:BOOL=OFF
    #   working-directory: ${{ github.workspace }}
    # - name: Build
    #   run: |
    #     cmake --build --preset linux-gcc-release-build --target install
    #   working-directory: ${{ github.workspace }}
    # - name: Upload library
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: mumps-linux-gcc
    #     path: ${{ github.workspace }}/out/install/linux-gcc-release-config
    - name: did it work
      run: |
        env
      shell: bash
